version: "3.9"

services:
  shiny:
    build: ./containers/shiny
    ports:
      - 3838:3838
    volumes:
      - ./app:/srv/shiny-server/
      - ./logs:/var/log/shiny-server/
      - ./data:/data/
    command: ["/usr/bin/shiny-server"]
  redis:
    build: ./containers/redis
    ports:
      - 6379:6379
      - 3000:3000
    volumes:
      - ./data:/data
      - ./conf:/usr/local/etc/redis/
      - ./:/local
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
